Fix IR compile: Workaround Guile encoding problem.
NOTE: this patch is only a workaround, not appropriate to merge with master.

Guile is having some UTF-8 troubles:

  ERROR: In procedure display:
  ERROR: Throw to key `encoding-error' with args `("iprin1" "cannot
  convert to output locale" 84 #<output: string 43fa340> #\1700)'.

The code #\1700 is the Greek lowercase pi.

TODO: report upstream