Try to fix "TypeError: a bytes-like object is required, not 'str'"
  File "/home/knut/sources/lily/scripts/lilypond-book.py", line 418, in process_snippets
    open (name, 'wb').write (contents)
TypeError: a bytes-like object is required, not 'str'