Fix IR compile: Comment out code that doesn't compile.
NOTE1: this patch is only a workaround, not appropriate to merge with master.

NOTE2: this commit breaks info doc generation later on in the make process.

from the log:

;;; compiling /home/pnorcks/git/lilypond/scm/document-backend.scm
;;; compiled /home/pnorcks/.cache/guile/ccache/2.0-LE-8-2.0/home/pnorcks/git/lilypond/scm/document-backend.scm.go
Backtrace:
In ice-9/boot-9.scm:
 170: 18 [catch #t #<catch-closure 21ec360> ...]
In unknown file:
   ?: 17 [catch-closure]
In /home/pnorcks/git/lilypond/scm/lily.scm:
 812: 16 [lilypond-main #<variable 3e45b50 value: #>]
 836: 15 [lilypond-all ("/home/pnorcks/git/lilypond/ly/generate-documentation")]
In srfi/srfi-1.scm:
 584: 14 [for-each #<procedure 355c340 at /home/pnorcks/git/lilypond/scm/lily.scm:837:5 (x)> ...]
In /home/pnorcks/git/lilypond/scm/lily.scm:
 849: 13 [#<procedure 355c340 at /home/pnorcks/git/lilypond/scm/lily.scm:837:5 (x)> "/home/pnorcks/git/lilypond/ly/generate-documentation"]
In ice-9/boot-9.scm:
 170: 12 [catch ly-file-failed ...]
In unknown file:
   ?: 11 [ly:parse-file "/home/pnorcks/git/lilypond/ly/generate-documentation"]
In ice-9/boot-9.scm:
1375: 10 [%start-stack load-stack #<procedure 26e0120 at ice-9/boot-9.scm:1397:2 ()>]
1380: 9 [#<procedure 37ba930 ()>]
In unknown file:
   ?: 8 [primitive-load-path "documentation-generate.scm"]
In /home/pnorcks/git/lilypond/scm/documentation-generate.scm:
  30: 7 [#<procedure 234e120 ()>]
In srfi/srfi-1.scm:
 545: 6 [map #<procedure ly:load (x)> #]
In /home/pnorcks/git/lilypond/scm/lily.scm:
 293: 5 [ly:load "document-backend.scm"]
In unknown file:
   ?: 4 [primitive-load-path "/home/pnorcks/git/lilypond/out/share/lilypond/current/scm/document-backend.scm"]
In /home/pnorcks/git/lilypond/scm/document-backend.scm:
  27: 3 [#<procedure 2c18e60 ()>]
In srfi/srfi-1.scm:
 545: 2 [map #<procedure 2c18d60 at /home/pnorcks/git/lilypond/scm/document-backend.scm:28:2 (x)> ...]
In /home/pnorcks/git/lilypond/scm/document-backend.scm:
  37: 1 [#<procedure 2c18d60 at /home/pnorcks/git/lilypond/scm/document-backend.scm:28:2 (x)> #]
In unknown file:
   ?: 0 [sort #f #<procedure ly:symbol-ci<? (a b)>]

ERROR: In procedure sort:
ERROR: In procedure sort: Wrong type argument in position 1: #f